export const HOME_ROUTE = '/'
export const LOGIN_ROUTE = '/login'
export const PROFILE_ROUTE = '/profile'
export const TASKS_ROUTE = '/tasks'
export const ACTIVETASKS_ROUTE = '/activetasks'
export const ADD_TASK = '/addtask'
export const SIGNOUT_ROUTE = '/signout'